# Generated by Django 4.0.6 on 2022-07-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwrk', '0002_message_cname_message_ip_message_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
